### ISSUE TITLE
java.lang.NullPointerException error

### ISSUE THREAD

**Issue by bunk3m** [languagetool-org/languagetool-for-libreoffice#12] opened 2024-01-12 21:35 UTC
I received a presentation (PPTX) that was created on Google Docs.
When I try to open the document an error message pops up.
As far as I can tell, it didn't break something in the document but I thought I should post in case anyone else sees this.
Windows 11 64 bit (current as of Jan 12, 2024)
Java version 21.0.1 from Eclipse Adoptium
Libreoffice 7.6.4.1 (X86_64) : Build e19e193f88cd6c0525a17fb7a176ed8e6a3e2aa1
LanguageTool 6.3.1

![image](https://github.com/languagetool-org/languagetool/assets/3494567/83a213b9-04d4-4172-8622-339b35da9370)

**Comment by FredKruse** [comment] 2024-02-06 12:01
The bug is solved. Please test it with the next nightly, tomorrow.
Please close the issue if it's fixed.

**Comment by FredKruse** [comment] 2024-07-03 15:25
The issue is solved, I close it.

This branch will not be continued. The LibreOffice extension based on LanguageTool will now be continued under the name WritingTool (see here: https://github.com/FredKruse/writingtool). A repository for snapshots of WritingTool will also be named there shortly.
Please report any errors in the current extension (LanguaugeTool 6.4) here:  https://github.com/FredKruse/writingtool/issues

**Closed as completed by FredKruse** 2024-07-03 15:25 UTC
